package: yconverter
version: '2.0.0-dev'
author: Thomas Blum
supportpage:

page:
    title: 'translate:title'
    perm: admin[]
    icon: rex-icon fa-life-ring
    subpages:
        convert:
            title: 'translate:subpage_convert'
            subpages:
                redaxo: { title: 'translate:subpage_redaxo' }
                xform: { title: 'translate:subpage_xform' }
        settings: { title: 'translate:subpage_settings' }

requires:
    redaxo: ^5.6.5
